version: '3.7'

services:
  balancer:
    image: nginx
    container_name: nginx
    restart: on-failure
    ports:
      - "8181:80"
    networks:
      front-tier:
        ipv4_address: 172.12.5.10

  frontend-server1:
    image: httpd-server1
    container_name: httpd-server1
    restart: on-failure
    # enviroment:

    # volumes:

    # ports:

    networks:
      front-tier:
        ipv4_address: 172.12.5.11
      back-tier:
        ipv4_address: 172.12.6.100

  frontend-server2:
    image: httpd-server2
    container_name: httpd-server2
    restart: on-failure
    # enviroment:

    # volumes:

    # ports:

    networks:
      front-tier:
        ipv4_address: 172.12.5.12
      back-tier:
        ipv4_address: 172.12.6.101


  # backend-server1:
  #   image: tomcat-server1
  #   container_name: tomcat-server1
  #   restart: on-failure
  #   # enviroment:

  #   # volumes:

  #   # ports:

  #   networks:
  #     back-tier:
  #       ipv4_address: 172.12.6.102

  # backend-server2:
  #   image: tomcat-server2
  #   container_name: tomcat-server2
  #   restart: on-failure
  #   # enviroment:

  #   # volumes:

  #   # ports:

  #   networks:
  #     back-tier:
  #       ipv4_address: 172.12.6.103

networks:
  front-tier:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.12.5.0/24"
          gateway: "172.12.5.1"

  back-tier:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.12.6.0/24"
          gateway: "172.12.6.1"


